# Generated by Django 4.2.11 on 2024-08-21 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuits',
            fields=[
                ('url', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=120, null=True)),
                ('circuit_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=60)),
                ('locality', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('country', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('turns', models.IntegerField(blank=True, null=True)),
                ('circuit_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'circuits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Constructors',
            fields=[
                ('constructor_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=30, primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=120, null=True)),
                ('constructor_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
            ],
            options={
                'db_table': 'constructors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('driver_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=30, primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=120, null=True)),
                ('given_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('family_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
            ],
            options={
                'db_table': 'drivers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Laptime',
            fields=[
                ('laptime_id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('time_in_ms', models.BigIntegerField(blank=True, null=True)),
                ('season', models.IntegerField(blank=True, null=True)),
                ('round', models.IntegerField(blank=True, null=True)),
                ('lap', models.IntegerField(blank=True, null=True)),
                ('driver_id', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=30, null=True)),
            ],
            options={
                'db_table': 'laptime',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pitstops',
            fields=[
                ('pitstop_id', models.AutoField(primary_key=True, serialize=False)),
                ('season', models.IntegerField(blank=True, null=True)),
                ('round', models.IntegerField(blank=True, null=True)),
                ('driver_id', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=30, null=True)),
                ('lap', models.IntegerField(blank=True, null=True)),
                ('stop', models.IntegerField(blank=True, null=True)),
                ('time', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=30, null=True)),
                ('duration_in_ms', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pitstops',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Qualifying',
            fields=[
                ('qualifying_id', models.AutoField(primary_key=True, serialize=False)),
                ('season', models.IntegerField(blank=True, null=True)),
                ('round', models.IntegerField(blank=True, null=True)),
                ('driver_id', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=30, null=True)),
                ('qualifying_position', models.IntegerField(blank=True, null=True)),
                ('q1_in_ms', models.BigIntegerField(blank=True, null=True)),
                ('q2_in_ms', models.BigIntegerField(blank=True, null=True)),
                ('q3_in_ms', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'qualifying',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Races',
            fields=[
                ('season', models.IntegerField(primary_key=True, serialize=False)),
                ('round', models.IntegerField()),
                ('url', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=120, null=True)),
                ('race_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('time', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, null=True)),
                ('first_practice_datetime', models.DateTimeField(blank=True, null=True)),
                ('second_practice_datetime', models.DateTimeField(blank=True, null=True)),
                ('third_practice_datetime', models.DateTimeField(blank=True, null=True)),
                ('qualifying_datetime', models.DateTimeField(blank=True, null=True)),
                ('sprint_datetime', models.DateTimeField(blank=True, null=True)),
                ('circuit_id', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'races',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('season', models.IntegerField(blank=True, null=True)),
                ('round', models.IntegerField(blank=True, null=True)),
                ('driver_id', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=30, null=True)),
                ('constructor_id', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=30, null=True)),
                ('number', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('finished_position', models.IntegerField(blank=True, null=True)),
                ('points', models.FloatField(blank=True, null=True)),
                ('grid', models.IntegerField(blank=True, null=True)),
                ('laps', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('time_in_ms', models.BigIntegerField(blank=True, null=True)),
                ('fastest_lap_rank', models.IntegerField(blank=True, null=True)),
                ('fastest_lap_lap', models.IntegerField(blank=True, null=True)),
                ('fastest_lap_time', models.BigIntegerField(blank=True, null=True)),
                ('average_speed_kph', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'results',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeasonDrivingStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(blank=True, null=True)),
                ('driver_id', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=30, null=True)),
                ('points', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'season_driving_standing',
                'managed': False,
            },
        ),
    ]
